#!/bin/bash
#SBATCH --job-name=yolo_contr             # Job name
#SBATCH --output=cluster_out/trainval_bests.%A_%a.txt   # Standard output and error log
#SBATCH --nodes=1                   # Run all processes on a single node    
#SBATCH --ntasks=1                  # Run on a single CPU
#SBATCH --mem=40G                   # Total RAM to be used
#SBATCH --cpus-per-task=24          # Number of CPU cores
#SBATCH --gres=gpu:1                # Number of GPUs (per node)
#SBATCH -p gpu                      # Use the gpu partition
#SBATCH --time=12:00:00             # Specify the time needed for your experiment
#SBATCH --qos=gpu-8                 # To enable the use of up to 8 GPUs

hostname
/home/jameel.hassan/.conda/envs/yolo/bin/python inference.py --project runs/detect/v8m --checkpoint yolov8m.pt --experiment Best_again --close_mosaic 5 --mosaic_prob 1 --contr_loss 0.2 --queue_size 50 --contr_ema_iters 200 --contr_calib